### ISSUE TITLE
Is nesting default content in ui-view supported?

### ISSUE THREAD

**Issue by thebearingedge** [TehShrike/riot-state-renderer#5]
First off, thanks so much for making these libraries. I was beginning to wonder if anyone would ever attempt this besides UI Router, React Router and Ember. Mad props!!!

I'm wondering if there is a way to batch-render/update the app's view in one go after a state transition. If I do this, I get a flash of `app-root` until my nested state template tag is mounted:

``` jade
app-shell

  h1 { title }
  ui-view
    app-root

  script.
    this.title = 'Riot with a kickass router (and jade templates, thank god)!'
```

Adding an `if` attribute to `app-root` seems to do the trick, but I wonder if the state renderer or router can already do what I want.

``` jade
ui-view
  app-root(if='{ !appRoot }')
```

Is nesting default content in `ui-view` supported?

**Comment by TehShrike** [comment]
Rendering the template of a child state relies on the fact that the parent template already exists in the DOM, and is able to point to the ui-view element where the child can be rendered.

This rules out having everything rendered at once, but the upside is that if you're at the `app.welcome` state and you transition to `app.getToWork`, the template of the `app` state doesn't have to re-render at all (though if any relevant parameters changed, it will get [reset](https://github.com/TehShrike/riot-state-renderer/blob/master/index.js#L38-L42) before its new context is activated).

I think the best practical choice is to leave the ui-view elements empty in each template, because any contents could only be visible for a flash [between the reset and render steps](https://github.com/TehShrike/abstract-state-router#state-change-flow).

I have thought about adding some way to indicate in the DOM that certain states were "loading" or "transitioning" right away when the state change starts, as opposed to the current behavior, which leaves the old state's DOM around until all of the resolve functions come back.  I'm not sure how to best pull it off though - it seems safer to leave the old state around in case some error happens during a resolve or activation.  I dunno.

Did I understand your question correctly?  What sort of default content were you envisioning?

**Comment by TehShrike** [comment]
oh wait, I think I might have figured out what you were getting at - you have an `app` state with a `gettingThingsDone` child that they see when they visit `/app/getting-things-done`, but you want them to be able to browse to `/app` and see that space with some other, default content in it.  Is that right?

If so, that is possible - put that default content in a separate child state, like `app.welcome` or something, and then set the `defaultChild` property to `'welcome'` when [adding the app state](https://github.com/TehShrike/abstract-state-router#staterouteraddstatename-route-defaultchild-data-template-resolve-activate-querystringparameters).

The [example site uses this](https://github.com/TehShrike/state-router-example/blob/gh-pages/implementations/riot/app/app.js#L10) to send people to the `app.topics` state when they browse to `app`.

**Comment by thebearingedge** [comment]
Okay, your second post pointed me in the right direction. I was still thinking in terms of UI Router.

I was reading ["If you attempt to go directly to a state that has a default child, you will be directed to the default child"](https://github.com/TehShrike/abstract-state-router#staterouteraddstatename-route-defaultchild-data-template-resolve-activate-querystringparameters) to mean that the URL hash would also change to match the child's route. Really the default child view gets rendered but the hash is not updated. Thus, `defaultChild` covers exactly what I was looking for, thank you!

On a related note, I was incorrectly assuming that `stateRouter.evaluateCurrentRoute(fallbackRoute)` would also set the hash to match the fallback state's route. Maybe it should. As it is now, unmatched routes are getting added to the window's history.

With regards to transitions, I can't supply any input yet. Once I have a basic set of states and views put together I will see if I run into any issues. I really like being able to do a subtle fade-out fade-in of views but I haven't tried it outside of Angular yet and need time with Riot too. Will let you know.

**Comment by ArtskydJ** [comment]
> Really the default child view gets rendered but the hash is not updated.

I believe the hash is updated.

If the default child of `a` is `b`, then browsing to `#/a`, or doing `state.go('a')` will bring you to the `a.b` state, and will update the hash to `#/a/b`.

Is this correct @TehShrike?

**Comment by TehShrike** [comment]
Hmm, yeah, it should be updating the route in the url in both cases.  Do you have an example where that's not happening?

The thing is, though, that you don't need to supply a url for the child states at all.  You could add your default child state with an undefined url and it should work fine.

**Comment by TehShrike** [comment]
I believe with the recent improvements to default child states, this should be good.
